version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: dashmap
        update-types:
          - version-update:semver-major
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - patch
  - package-ecosystem: cargo
    directory: /editors/zed
    schedule:
      interval: weekly
    groups:
      zed-cargo:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /fuzz
    schedule:
      interval: weekly
    allow:
      - dependency-name: libfuzzer-sys
    groups:
      fuzz-cargo:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
    groups:
      root-node:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /editors/vscode
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "@types/node"
    groups:
      vscode:
        patterns:
          - "*"
