/* @generated by Wesley. Do not edit. */

export interface ByteRange {
  startUtf8: number;
  endUtf8: number;
}

export interface DerivationStep {
  passId: string;
  ruleId: string;
  sourceRanges: ByteRange[];
  compilerBuildHash: string;
}

export interface Diagnostic {
  byteRange: ByteRange;
  severity: DiagnosticSeverity;
  code: string;
  message: string;
}

export type DiagnosticSeverity = "ERROR" | "WARNING" | "INFO";

export interface DocumentAnalysis {
  contractVersion: string;
  schemaHash: string;
  vocabularyHash: string;
  source: SourceArtifact;
  tokens: Token[];
  structure: OutlineNode[];
  diagnostics: Diagnostic[];
  derivation: DerivationStep[];
}

export type FunctionKind = "ARTICLE" | "PREPOSITION" | "CONJUNCTION" | "PRONOUN" | "AUXILIARY" | "DETERMINER" | "NEGATOR";

export type LexicalClass = "FUNCTION" | "CONTENT" | "PROPER_NOUN_CANDIDATE";

export type OutlineKind = "PARAGRAPH" | "SENTENCE";

export interface OutlineNode {
  nodeId: number;
  kind: OutlineKind;
  byteRange: ByteRange;
  depth: number;
  childNodeIds: number[];
}

export interface SourceArtifact {
  unitId: string;
  contentHash: string;
  utf8ByteLength: number;
}

export interface Token {
  occurrenceId: number;
  byteRange: ByteRange;
  tokenKind: TokenKind;
  lexicalClass: LexicalClass | null;
  functionKind: FunctionKind | null;
}

export type TokenKind = "WORD" | "NUMBER" | "PUNCTUATION" | "QUOTE";
